apiVersion: v1
kind: ConfigMap
metadata:
  name: commafeed
  namespace: commafeed

data:
  application.properties: |
    commafeed.database.cleanup.entries-max-age=7D
    commafeed.database.cleanup.max-feed-capacity=100
    commafeed.database.cleanup.statuses-max-age=7D
